version: '3.8'

services:
  vehicle-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicle_api
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/vehicle_db
      - DB_USER=vehicle_admin
      - DB_PASSWORD=adminpass
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: vehicle_management_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vehicle_db
      MYSQL_USER: vehicle_admin
      MYSQL_PASSWORD: adminpass
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: