# Test Configuration
# --------------------------
spring:
  application:
    name: vehicles-test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always

application:
  title: Vehicle Management System [TEST]
  version: 0.0.1-TEST
  api:
    version: v1
    base-path: /api

server:
  port: 0  # Random port for tests

# JWT Configuration (test keys)
jwt:
  private:
    key: classpath:test.key
  public:
    key: classpath:test.pub


logging:
  level:
    root: INFO
    org:
      hibernate: ERROR
      springframework: WARN
    com:
      yourpackage: DEBUG